### ISSUE TITLE
CI: Include black on GitHub Actions

### ISSUE THREAD

**Issue by aureliobarbosa** [ScientificThought/py-math-interpreter#24]
Tutorial below

https://black.readthedocs.io/en/stable/integrations/github_actions.html

**Comment by aureliobarbosa** [comment]
I think the code below can be incorporated into the workflow (or within a new workflow file).
From the ref. above.

```yaml
name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
          with:
             options: "--check --verbose"
#           I am in doubt if the code below will work. Original code was # src: "./src"
             src: ["./mathinterpreter", "./tests"]
             use_pyproject: true
```
